Fixed exception handling for createFile and createDir function calls
y0014984/Advanced-Equipment pull request #256
Opened 2022-11-27 17:33 UTC by y0014984

By merging this Pull Request every call of createDir or createFile function is embedded in a try/catch-block. Both functions thow errors if the filesystem object already exists. This happens for example if you snyc identical modules multiple times to the same computer. The exceptions are now logged in the *.rpt file.

2022-12-07 21:07 UTC, GermanHydrogen requested changes

2022-12-07 21:07 UTC, GermanHydrogen commented on addons/filesystem/functions/fnc_initFilesystem.sqf
> +		} catch { diag_log format ["AE3 exception: %1", _exception]; };
To broad catch. Would be better, if other exceptions are still raised

2022-12-07 21:07 UTC, GermanHydrogen commented on addons/filesystem/functions/fnc_initFilesystem.sqf
> +		} catch { diag_log format ["AE3 exception: %1", _exception]; };
See above

2022-12-07 21:07 UTC, GermanHydrogen commented on addons/filesystem/functions/fnc_moduleAddDir.sqf
> +		} catch { diag_log format ["AE3 exception: %1", _exception]; };
See above

2022-12-07 21:07 UTC, GermanHydrogen commented on addons/filesystem/functions/fnc_moduleAddFile.sqf
> +		} catch { diag_log format ["AE3 exception: %1", _exception]; };
see above

2022-12-09 08:46 UTC, y0014984 commented
@GermanHydrogen ,I modified the catch clauses to only catch 'already exists' exceptions, so other exceptions are still thrown. It was a bit complicated because the exception is not a fixed string but contains the name of the filesystem object that already exists. So I needed to regExReplace the dynamic content for example `'home' already exists!` to look like this `'%1' already exists!`. This this the `format` string, that is used to build the dynamic exception. So, I can use this to compare the strings in the `if` clause.

2022-12-09 09:10 UTC, GermanHydrogen approved these changes

2022-12-09 12:31 UTC, merged